### ISSUE TITLE
npm create gnome-extension@latest not working

### ISSUE THREAD

**Issue by dagimg-dot** [Leleat/create-gnome-extension#49]
it shows the following error

npm error code 128
npm error path /home/jd/.npm/_npx/752346eaeaa99e26/node_modules/create-gnome-extension
npm error command failed
npm error command sh -c git config --local core.hooksPath .githooks
npm error fatal: --local can only be used inside a git repository

npm error A complete log of this run can be found in: /home/jd/.npm/_logs/2024-07-17T20_46_59_095Z-debug-0.log

**Comment by Leleat** [comment]
Hmm, this is weird... I understand why the error would happen but for some reason I can't reproduce this on my linux machine. I can however reproduce this on my MacBook. Weird, but okay. I've made a new release that fixes this.

**Comment by Leleat** [comment]
I think I've figured out why I didn't get this error on my linux machine. On my linux desktop I've turned the entire home directory into a git repo to save my dotfiles. So when running the `git config --local core.hooksPath .githooks` command, git was traveling up the file tree until it hit my home directory and set the config there, heh.

**Comment by dagimg-dot** [comment]
> I think I've figured out why I didn't get this error on my linux machine. On my linux desktop I've turned the entire home directory into a git repo to save my dotfiles. So when running the `git config --local core.hooksPath .githooks` command, git was traveling up the file tree until it hit my home directory and set the config there, heh.

oww okay....why are you not using stow or some other utility instead of making home a git repo?

**Comment by Leleat** [comment]
Just laziness/convenvience. Instead of needing to pick up a new tool (which I probably need to look up how to use everytime since I probably don't need to use it often). I'm just gonna use a tool that I am already familiar with... and usually it just works™ .
